---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - elasticweb.my.com
  resources:
  - elasticwebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticweb.my.com
  resources:
  - elasticwebs/finalizers
  verbs:
  - update
- apiGroups:
  - elasticweb.my.com
  resources:
  - elasticwebs/status
  verbs:
  - get
  - patch
  - update
